name: "${project.artifactId}"
main: "${project.groupId}.${project.artifactId}"
version: "${project.version}"
author: "BillyGalbreath"
description: "Minimalistic and lightweight world map viewer for Paper servers"
api-version: "1.16"
softdepend:
  - Pl3xMapServer

permissions:
  command.pl3xmap:
    description: Control the plugin
    default: op
